m1ct_node:
  ros__parameters:
    #robot frame
    frame_id: laser_link       

    #serial
    serial_port: /dev/tarkbot_lidar
    serial_baudrate: 115200
    cut_angle: true
    start_angle: 130
    end_angle: 230





