rplidar_node:
  ros__parameters:
    #robot frame
    frame_id: laser_link       

    #serial
    serial_port: /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-port0 #/dev/tarkbot_lidar
    serial_baudrate: 115200
    cut_angle: true
    start_angle: 130
    end_angle: 230





