xtlidar_driver2_node:
  ros__parameters:
    type: "uart"
    platform: "LDS-50C-2"
    port: "/dev/xtark_lidar"
    frame_id: "laser_link"
    rate_list: "768000, 921600"
    baud_rate: 768000
    raw_bytes: 3
    max_dist: 25.0
    output_360: true
    output_scan: true
    output_cloud: false
    with_angle_filter: true
    min_angle: -2.1
    max_angle: 2.1
    hard_resample: true
    soft_resample: false
    resample_res: 0.25
    unit_is_mm: true
    with_confidence: true
    with_checksum: true
    #rpm: 600
    with_smooth: true
    with_deshadow: true
    inverted: false
    reversed: false
    lidar_ip: "192.168.158.91"
    lidar_port: 6543
    local_port: 6666
    group_ip: "224.1.2.3"
    dev_id: 0
