tarkbot_robot_node:
  ros__parameters:
    #robot frame
    base_frame: base_footprint    
    odom_frame: odom         
    imu_frame: imu_link      

    #pub topic
    odom_topic: odom
    imu_topic: imu
    battery_topic: bat_vol

    #sub topic
    cmd_vel_topic: cmd_vel
    
    #config param
    robot_port: /dev/ttyAMA0    
    pub_odom_tf: true
    akm_servo_offset: -40 



